CREATE INDEX Prisoner_Last_Name_IDX ON Prisoner(Last_Name);
CREATE INDEX Prisoner_Block_IDX ON Prisoner(Block);
CREATE INDEX Prisoner_Room_IDX ON Prisoner(Room);
CREATE INDEX Prisoner_Date_Of_Birth_IDX ON Prisoner(Date_Of_Birth);
CREATE INDEX Visit_Date_IDX ON Visit(Visit_Date);
CREATE INDEX Visit_Visitor_Last_Name_IDX ON Visit(Visitor_Last_Name);
CREATE INDEX Employee_Last_Name_IDX ON Employee(Last_Name);
CREATE INDEX Employee_Job_Title_IDX ON Employee(Job_Title);
CREATE INDEX Duty_Schedule_Date_IDX ON Duty_Schedule(Date);
CREATE INDEX Conscription_Date_IDX ON Conscription(Date);
CREATE INDEX Punishment_Start_Date_IDX ON Punishment(Start_Date);
CREATE INDEX Punishment_End_Date_IDX ON Punishment(End_Date);
CREATE INDEX Prisoner_Last_First_Name_IDX ON Prisoner(Last_Name, First_Name);
CREATE INDEX Prisoner_Block_Room_IDX ON Prisoner(Block, Room);
CREATE INDEX Visit_Prisoner_Date_IDX ON Visit(Prisoner_ID, Visit_Date);
CREATE INDEX Visit_Employee_Date_IDX ON Visit(Employee_ID, Visit_Date);
CREATE INDEX Punishment_Dates_IDX ON Punishment(Start_Date, End_Date);
CREATE INDEX Duty_Schedule_Employee_Date_IDX ON Duty_Schedule(Employee_ID, Date);